### ISSUE TITLE
Missing string quote in CMakeLists.txt

### ISSUE THREAD

**Issue by waebbl** [yayahjb/cbflib#27]
There's a missing ending string quote in the cmake file at
https://github.com/yayahjb/cbflib/blob/6f8cb004d29b3537cb4942a1be88dbb6c5da712e/CMakeLists.txt#L1098

**Comment by yayahjb** [comment]
Fixed.  Thank you. -- Herbert

**Comment by yayahjb** [comment]
Fixed.  Thank you.

**Comment by waebbl** [comment]
Sorry to bother you again. Noticed the color formatting is still not correct, when viewing the file in the browser and by this I noticed another such issue at

https://github.com/yayahjb/cbflib/blob/2650f7478e53ec96a4284c0086848f4f70a9c114/CMakeLists.txt#L1090

**Comment by yayahjb** [comment]
Fixed.  Thank you. -- Herbert
